package slave1;

public enum Slave1Input {
	START, NSTOP, ESTOP, RESTART, AXIS_IN_AS, GEAR_IN_AS, AS_IN_TRANSPORT, AUTO_FEED_AXIS_ON, AUTO_FEED_AXIS_OFF, AUTO_FEED_GEAR_ON, AUTO_FEED_GEAR_OFF, MOVE_AXIS, MOVE_GEAR;

	//	EMPTY_TRANSFER_CB,AS_EMPTY, 
}
