package slave1;

public enum Slave1Input {
	START,
	EMPTY_TRANSFER_CB,
	FEED_AXIS,
	FEED_GEAR,
	AUTO_FEED_AXIS_ON,
	AUTO_FEED_AXIS_OFF,
	AUTO_FEED_GEAR_ON,
	AUTO_FEED_GEAR_OFF, ESTOP, NSTOP, RESTART, AS_EMPTY
}
