package master;

public enum MasterInput {
	START,
	EMPTY_TRANSFER_CB,
	FEED_AXIS,
	FEED_GEAR,
	AUTO_FEED_AXIS_ON,
	AUTO_FEED_AXIS_OFF,
	AUTO_FEED_GEAR_ON,
	AUTO_FEED_GEAR_OFF, ESTOP, NSTOP, RESUME
}
